services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: team_hadoop
      MYSQL_DATABASE: comparateur_prix
      MYSQL_USER: hadoop
      MYSQL_PASSWORD: team_hadoop
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: team_hadoop
    ports:
      - "8080:80"
    depends_on:
      - db

  scraper:
    build: 
      context: ./scrapy_app
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./scrapy_app:/app

volumes:
  mysql_data: